# PostgreSQL Ba?lant? Ayarlar?
spring.datasource.url=jdbc:postgresql://localhost:5432/saferoute_db
spring.datasource.username=postgres
spring.datasource.password=senindatabaseşifren

# JPA & Hibernate Ayarlar?
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# "update" sayesinde biz entity olu?turdukça tablolar otomatik güncellenir
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
